---
name: GitHub Actions runner
version: 1.0.2
slug: github_actions_runner
description: Runner for GitHub Actions
url: https://github.com/Astavelopment-Home-Assistant/homeassistant-addons
codenotary: kdosiodjinud@gmail.com
startup: system
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  runners: []
schema:
  runners:
    - url: str
      token: str
      name: str
      labels: str

